---
kind: ConfigMap
apiVersion: v1
metadata:
  name: console-configuration
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
{{ (.Files.Glob "files/console/nginx.conf").AsConfig | indent 2 }}

  app.conf: |
{{ (.Files.Glob "files/console/app.conf").AsConfig | indent 2 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concord-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concord-console
  template:
    metadata:
      labels:
        app: concord-console
    spec:
      containers:
        - name: concord-console
          image: {{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - name: "console-configuration-mnt"
            mountPath: /opt/concord/console/nginx
          ports:
          - containerPort: {{ .Values.console.port }}
      volumes:
      - name: console-configuration-mnt
        configMap:
          name: console-configuration
---
apiVersion: v1
kind: Service
metadata:
  name: concord-console
  labels:
    app: concord-console
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.console.port }}
    protocol: TCP
  selector:
    app: concord-console
