---
kind: ConfigMap
apiVersion: v1
metadata:
  name: server-conf
data:
{{ (tpl (.Files.Glob "files/server/server.conf").AsConfig . ) | indent 2 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concord-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concord-server
  template:
    metadata:
      labels:
        app: concord-server
    spec:
      containers:
        - name: concord-server
          image: {{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - name: "cfg"
            mountPath: "/opt/concord/conf/server.conf"
            subPath: server.conf
          ports:
          - containerPort: {{ .Values.server.port }}
          env:
          - name: CONCORD_CFG_FILE
            value: /opt/concord/conf/server.conf
          {{- if not .Values.server.git.ssl.verify }}
          - name: GIT_SSL_NO_VERIFY
            value: "true" # use quotes!
          {{- end }}
      volumes:
        - name: cfg
          configMap:
            name: server-conf
---
apiVersion: v1
kind: Service
metadata:
  name: concord-server
{{- if .Values.server.annotations }}
{{- with .Values.server.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
  labels:
    app: concord-server
spec:
  type: {{ .Values.server.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.server.port }}
    protocol: TCP
  selector:
    app: concord-server
