---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
data:
{{ (.Files.Glob "files/nginx.conf").AsConfig | indent 2 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-conf
data:
{{ (.Files.Glob "files/app.conf").AsConfig | indent 2 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concord-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concord-console
  template:
    metadata:
      labels:
        app: concord-console
    spec:
      containers:
        - name: concord-console
          image: ibodrov/concord-console:latest
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - name: "nginx-conf-mnt"
            mountPath: /opt/concord/console/nginx/nginx.conf
            subPath: nginx.conf
          - name: "app-conf-mnt"
            mountPath: /opt/concord/console/nginx/app.conf
            subPath: app.conf
          ports:
          - containerPort: 8001
      volumes:
      - name: nginx-conf-mnt
        configMap:
          name: nginx-conf
      - name: app-conf-mnt
        configMap:
          name: app-conf
---
apiVersion: v1
kind: Service
metadata:
  name: concord-console
  labels:
    app: concord-console
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: concord-console
